
############################################################
=TITLE=Merge routing Linux
=DEVICE=
#NONE
=NETSPOC=
--router
ip route add 10.20.0.0/19 via 10.1.2.3
ip route add 10.23.0.0/16 via 10.1.2.5
--router.raw
ip route add 10.22.0.0/16 via 10.1.2.4
ip route add 10.0.0.0/8 via 10.1.2.2
=OUTPUT=
ip route add 10.20.0.0/19 via 10.1.2.3
ip route add 10.23.0.0/16 via 10.1.2.5
ip route add 10.22.0.0/16 via 10.1.2.4
ip route add 10.0.0.0/8 via 10.1.2.2
=END=

############################################################
=TITLE=Merge Linux chains
=NETSPOC=
--router
*filter
:INPUT DROP
-A INPUT -i eth0 -s 10.0.6.0/24 -d 10.0.1.11/32 -p udp --dport 123 -j ACCEPT
-A INPUT -j DROP
--router.raw
*mangle
:PREROUTING ACCEPT
-A PREROUTING -j MARK --set-xmark 0x01 -p TCP --dport 80
*filter
:INPUT DROP
:c1 -
-A c1 -s 10.0.6.0/24 -j ACCEPT
-A INPUT -i eth0 -p udp -d 224.0.1.1/32 --dport 123 -j c1
[APPEND]
-A INPUT -i eth0 -p udp -d 224.0.1.1/32 --dport 123 -j DROP
=OUTPUT=
iptables differs at [tables: <->filter,mangle]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:INPUT DROP
:c1 -
-A INPUT -i eth0 -p udp -d 224.0.1.1/32 --dport 123 -j c1
-A INPUT -i eth0 -s 10.0.6.0/24 -d 10.0.1.11/32 -p udp --dport 123 -j ACCEPT
-A INPUT -i eth0 -p udp -d 224.0.1.1/32 --dport 123 -j DROP
-A INPUT -j DROP
-A c1 -s 10.0.6.0/24 -j ACCEPT
COMMIT
*mangle
:PREROUTING ACCEPT
-A PREROUTING -j MARK --set-xmark 0x01 -p TCP --dport 80
COMMIT
=END=

############################################################
=TITLE=Must not reference Netspoc generated chain
=NETSPOC=
--router
*filter
:INPUT DROP
:c1 -
-A c1 -s 10.0.6.0/24 -j ACCEPT
-A INPUT -i eth0 -p udp -d 224.0.1.1/32 --dport 123 -j c1
--router.raw
*filter
:c1 -
-A c1 -s 10.0.7.0/24 -j ACCEPT
=ERROR=
ERROR>>> Must not redefine chain "c1" of table "filter" from rawdata
=END=
