
############################################################
=TITLE=Chain policy outside of table
=NETSPOC=
:c1 -
=ERROR=
ERROR>>> Found chain policy outside of table: ":c1 -"
=END=

############################################################
=TITLE=Rule outside of table
=NETSPOC=
-A c2 -g c1 -d 10.1.1.2 -p icmp
=ERROR=
ERROR>>> Found rule outside of table: "-A c2 -g c1 -d 10.1.1.2 -p icmp"
=END=

############################################################
=TITLE=Rule preceeds ist policy
=NETSPOC=
*filter
-A c2 -g c1 -d 10.1.1.2 -p icmp
=ERROR=
ERROR>>> Must define policy before adding rules of chain "c2"
=END=

############################################################
=TITLE=Unsupported command
=NETSPOC=
*filter
-I c2 -g c1 -d 10.1.1.2 -p icmp
=ERROR=
ERROR>>> Unsupported command "-I"
=END=

############################################################
=TITLE=Incomplete command
=NETSPOC=
*filter
 -A
=ERROR=
ERROR>>> Incomplete command "-A"
=END=

############################################################
=TITLE=Unknown command
=DEVICE=
foo
=NETSPOC=NONE
=ERROR=
ERROR>>> Unknown command: "foo"
=END=

############################################################
=TITLE=Unexpected trailing '!'
=DEVICE=
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -p TCP --syn !
=NETSPOC=NONE
=ERROR=
ERROR>>> Unexpected trailing '!' in line
ERROR>>>  -A FORWARD -i eth1 -j ACCEPT -p TCP --syn !
=END=

############################################################
=TITLE=Add ACL with chains and multiple tables
=TEMPL=iptables
#!/usr/sbin/iptables-restore <<EOF
*filter
:INPUT DROP
:FORWARD DROP
:OUTPUT ACCEPT
:eth0_self -
:eth0_in -
:c1 -
:c2 -
:c3 -
:c4 -
:c5 -
:c6 -
:droplog -
-A droplog -j LOG --log-level debug
-A droplog -j DROP
-A c1 -j ACCEPT -p icmp --icmp-type 0
-A c1 -j ACCEPT -p icmp --icmp-type 8
-A c2 -g c1 -d 10.1.1.2 -p icmp
-A c2 -g c1 -d 10.1.1.1 -p icmp
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 23
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.1 -p tcp --dport 23
-A c4 -j ACCEPT -p udp --dport 3400:3500
-A c4 -j ACCEPT -p udp --dport 3978
-A c5 -j c4 -p udp --dport 3000:4000
-A c5 -j ACCEPT -s 10.1.11.111 -p udp
-A c6 -g c5 -d 10.10.2.2
-A c6 -g c5 -d 10.10.2.1
-A eth0_self -j ACCEPT -s 10.1.1.0/24 -d 224.0.0.18 -p 112
-A eth0_self -g c2 -d 10.1.1.0/30 -p icmp
-A eth0_in -g c3 -d 10.10.1.0/30 -p tcp
-A eth0_in -g c6 -d 10.10.2.0/24 -p udp
-A INPUT -j ACCEPT -m state --state ESTABLISHED,RELATED
-A INPUT -j eth0_self -i eth0
-A INPUT -j droplog
-A FORWARD -j ACCEPT -m state --state ESTABLISHED,RELATED
-A FORWARD -j eth0_in -i eth0
-A FORWARD -j droplog
COMMIT
*nat
:OUTPUT ACCEPT
:PREROUTING ACCEPT
:POSTROUTING ACCEPT
-A POSTROUTING -j SNAT -s 10.1.2.3 -d 192.168.1.16/29 --to-source 10.2.3.4
COMMIT
=NETSPOC=[[iptables]]
# Full output.
# iptables rules are always transferred fully, not incementally.
=OUTPUT=
iptables differs at [tables: <->filter,nat]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:FORWARD DROP
:INPUT DROP
:OUTPUT ACCEPT
:c1 -
:c2 -
:c3 -
:c4 -
:c5 -
:c6 -
:droplog -
:eth0_in -
:eth0_self -
-A FORWARD -j ACCEPT -m state --state ESTABLISHED,RELATED
-A FORWARD -j eth0_in -i eth0
-A FORWARD -j droplog
-A INPUT -j ACCEPT -m state --state ESTABLISHED,RELATED
-A INPUT -j eth0_self -i eth0
-A INPUT -j droplog
-A c1 -j ACCEPT -p icmp --icmp-type 0
-A c1 -j ACCEPT -p icmp --icmp-type 8
-A c2 -g c1 -d 10.1.1.2 -p icmp
-A c2 -g c1 -d 10.1.1.1 -p icmp
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 23
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.1 -p tcp --dport 23
-A c4 -j ACCEPT -p udp --dport 3400:3500
-A c4 -j ACCEPT -p udp --dport 3978
-A c5 -j c4 -p udp --dport 3000:4000
-A c5 -j ACCEPT -s 10.1.11.111 -p udp
-A c6 -g c5 -d 10.10.2.2
-A c6 -g c5 -d 10.10.2.1
-A droplog -j LOG --log-level debug
-A droplog -j DROP
-A eth0_in -g c3 -d 10.10.1.0/30 -p tcp
-A eth0_in -g c6 -d 10.10.2.0/24 -p udp
-A eth0_self -j ACCEPT -s 10.1.1.0/24 -d 224.0.0.18 -p 112
-A eth0_self -g c2 -d 10.1.1.0/30 -p icmp
COMMIT
*nat
:OUTPUT ACCEPT
:POSTROUTING ACCEPT
:PREROUTING ACCEPT
-A POSTROUTING -j SNAT -s 10.1.2.3 -d 192.168.1.16/29 --to-source 10.2.3.4
COMMIT
=END=

############################################################
=TITLE=Unchanged ACL with chains and multiple tables
=DEVICE=[[iptables]]
=NETSPOC=[[iptables]]
=OUTPUT=NONE

############################################################
=TITLE=Add routing with iptables
=NETSPOC=
ip route add 10.10.0.0/16 via 10.1.2.3
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 22
=OUTPUT=
ip route add 10.10.0.0/16 via 10.1.2.3
iptables differs at [tables: <->filter]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 22
COMMIT
=END=

############################################################
=TITLE=Unchanged routing with iptables
=DEVICE=
ip route add 10.10.0.0/16 via 10.1.2.3
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 22
=NETSPOC=
ip route add 10.10.0.0/16 via 10.1.2.3
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 22
=OUTPUT=NONE

############################################################
=TITLE=Change chain policy
=DEVICE=
*filter
:INPUT DROP
-A INPUT -j ACCEPT -s 10.1.1.1 -d 10.1.2.1 -p tcp --dport 80
=NETSPOC=
*filter
:INPUT ACCEPT
-A INPUT -j DROP -s 10.1.1.1 -d 10.1.2.1 -p tcp --dport 80
=OUTPUT=
iptables differs at filter:INPUT:POLICY:[DROP<->ACCEPT]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:INPUT ACCEPT
-A INPUT -j DROP -s 10.1.1.1 -d 10.1.2.1 -p tcp --dport 80
COMMIT
=END=

############################################################
=TITLE=Use other chains
=DEVICE=
*filter
:INPUT DROP
-A INPUT -j ACCEPT -s 10.1.1.1 -d 10.1.2.1 -p tcp --dport 80
=NETSPOC=
*filter
:FORWARD DROP
-A FORWARD -j ACCEPT -s 10.1.1.1 -d 10.1.2.1 -p tcp --dport 80
=OUTPUT=
iptables differs at filter: [chains: INPUT<->FORWARD]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:FORWARD DROP
-A FORWARD -j ACCEPT -s 10.1.1.1 -d 10.1.2.1 -p tcp --dport 80
COMMIT
=END=

############################################################
=TITLE=Change iptables port
=DEVICE=
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 23
COMMIT
=NETSPOC=
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 22
COMMIT
=OUTPUT=
iptables differs at filter:c3:RULES:0:--dport:[23<->22]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 22
COMMIT
=END=

############################################################
=TITLE=Remove iptables port
=DEVICE=
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 23
COMMIT
=NETSPOC=
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp
COMMIT
=OUTPUT=
iptables differs at filter:c3:RULES:0:[options: --dport<->]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp
COMMIT
=END=

############################################################
=TITLE=Change iptables protocol
=DEVICE=
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 135
COMMIT
=NETSPOC=
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p udp --dport 135
COMMIT
=OUTPUT=
iptables differs at filter:c3:RULES:0:-p:[tcp<->udp]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p udp --dport 135
COMMIT
=END=

############################################################
=TITLE=Add iptables rule
=DEVICE=
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p udp --dport 135
COMMIT
=NETSPOC=
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p udp --dport 135
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p udp --dport 137
COMMIT
=OUTPUT=
iptables differs at filter:c3:RULES:[size: 1<->2]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p udp --dport 135
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p udp --dport 137
COMMIT
=END=

############################################################
=TITLE=Negation at option or at arg
=DEVICE=
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT ! -p TCP
=NETSPOC=
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -p ! TCP
=OUTPUT=NONE

############################################################
=TITLE=Protocol
=DEVICE=
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -p tcp
-A FORWARD -i eth1 -j ACCEPT -p 112
-A FORWARD -i eth1 -j ACCEPT -p 58
=NETSPOC=
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -p TCP
-A FORWARD -i eth1 -j ACCEPT -p vrrp
-A FORWARD -i eth1 -j ACCEPT -p IPV6-icmp
=OUTPUT=NONE

############################################################
=TITLE=Default values in port range
=DEVICE=
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -p TCP --dport 10000:65535 --sport 0:1023
-A FORWARD -i eth2 -j ACCEPT -p TCP --dport 0:65535
=NETSPOC=
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -p TCP --dport 10000: --sport :1023
-A FORWARD -i eth2 -j ACCEPT -p TCP --dport :
=OUTPUT=NONE

############################################################
=TITLE=TCP-flags as syn option
=DEVICE=
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -p TCP ! --syn
=NETSPOC=
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -p TCP ! --tcp-flags FIN,SYN,RST,ACK SYN
=OUTPUT=NONE

############################################################
=TITLE=Ignore option '-m'
=DEVICE=
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -m tcp -p TCP
=NETSPOC=
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -p TCP
=OUTPUT=NONE

############################################################
=TITLE=--set-mark identical to --xsetmark
=DEVICE=
*mangle
:PREROUTING ACCEPT
-A PREROUTING -j MARK --set-xmark 0x01 -p TCP --dport 80
-A PREROUTING -j MARK --set-xmark 0x0f/0xffffffff -p TCP --dport 81
=NETSPOC=
*mangle
:PREROUTING ACCEPT
-A PREROUTING -j MARK --set-mark 1 -p TCP --dport 80
-A PREROUTING -j MARK --set-mark 15 -p TCP --dport 81
=OUTPUT=NONE
