#!/bin/sh
# Wrapper script for newpolicy.pl
# Calls newpolicy.pl via "sudo" as "systemuser".

abort () { echo $@ >&2; exit 1; }

USER=$(get-netspoc-approve-conf systemuser)

[ -n "$USER" ] || abort 'Missing "systemuser" in config file'

# sudo needs to preserve environment variables
# - CVSROOT
# - LANG
# - PATH (needs /usr/local/bin)
exec sudo -u $USER /usr/local/bin/newpolicy.pl
