#!/usr/bin/perl
# Linux.t

use strict;
use warnings;
use Test::More;
use Test::Differences;
use lib 't';
use Test_Approve;

# Input from Netspoc.
# Input from device.
# Output from approve.
my($in, $device, $out);
my $type = 'Linux';
my $title;

my $minimal_device = '';

############################################################
$title = "Parse Routing";
############################################################
$in = <<END;
ip route add 10.1.11.1 via 10.10.1.7
ip route add 10.1.11.0/24 via 10.10.1.6
ip route add default via 10.9.9.9
END

$out = $in;

check_parse_and_unchanged($type, $minimal_device, $in, $out, $title);

############################################################
$title = "Parse ACL with chains und multiple tables";
############################################################
$in = <<END;
#!/usr/sbin/iptables-restore <<EOF
*filter
:INPUT DROP
:FORWARD DROP
:OUTPUT ACCEPT
:eth0_self -
:eth0_in -
:c1 -
:c2 -
:c3 -
:c4 -
:c5 -
:c6 -
:droplog -
-A droplog -j LOG --log-level debug
-A droplog -j DROP
-A c1 -j ACCEPT -p icmp --icmp-type 0
-A c1 -j ACCEPT -p icmp --icmp-type 8
-A c2 -g c1 -d 10.1.1.2 -p icmp
-A c2 -g c1 -d 10.1.1.1 -p icmp
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 23
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.1 -p tcp --dport 23
-A c4 -j ACCEPT -p udp --dport 3400:3500
-A c4 -j ACCEPT -p udp --dport 3978
-A c5 -j c4 -p udp --dport 3000:4000
-A c5 -j ACCEPT -s 10.1.11.111 -p udp
-A c6 -g c5 -d 10.10.2.2
-A c6 -g c5 -d 10.10.2.1

-A eth0_self -j ACCEPT -s 10.1.1.0/24 -d 224.0.0.18 -p 112
-A eth0_self -g c2 -d 10.1.1.0/30 -p icmp

-A eth0_in -g c3 -d 10.10.1.0/30 -p tcp
-A eth0_in -g c6 -d 10.10.2.0/24 -p udp

-A INPUT -j ACCEPT -m state --state ESTABLISHED,RELATED
-A INPUT -j eth0_self -i eth0
-A INPUT -j droplog
-A FORWARD -j ACCEPT -m state --state ESTABLISHED,RELATED
-A FORWARD -j eth0_in -i eth0
-A FORWARD -j droplog
COMMIT
*nat
:OUTPUT ACCEPT
:PREROUTING ACCEPT
:POSTROUTING ACCEPT
-A POSTROUTING -j SNAT -s 10.1.2.3 -d 192.168.1.16/29 --to-source 10.2.3.4
COMMIT
EOF
END

# Full output.
# iptables rules are always fully transferred, not incementally.
$out = <<'END';
iptables differs at [keys: <->filter,nat]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:FORWARD DROP
:INPUT DROP
:OUTPUT ACCEPT
:c1 -
:c2 -
:c3 -
:c4 -
:c5 -
:c6 -
:droplog -
:eth0_in -
:eth0_self -
-A FORWARD -j ACCEPT -m state --state ESTABLISHED,RELATED
-A FORWARD -j eth0_in -i eth0
-A FORWARD -j droplog
-A INPUT -j ACCEPT -m state --state ESTABLISHED,RELATED
-A INPUT -j eth0_self -i eth0
-A INPUT -j droplog
-A c1 -j ACCEPT -p icmp --icmp-type 0
-A c1 -j ACCEPT -p icmp --icmp-type 8
-A c2 -g c1 -d 10.1.1.2 -p icmp
-A c2 -g c1 -d 10.1.1.1 -p icmp
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 23
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.1 -p tcp --dport 23
-A c4 -j ACCEPT -p udp --dport 3400:3500
-A c4 -j ACCEPT -p udp --dport 3978
-A c5 -j c4 -p udp --dport 3000:4000
-A c5 -j ACCEPT -s 10.1.11.111 -p udp
-A c6 -g c5 -d 10.10.2.2
-A c6 -g c5 -d 10.10.2.1
-A droplog -j LOG --log-level debug
-A droplog -j DROP
-A eth0_in -g c3 -d 10.10.1.0/30 -p tcp
-A eth0_in -g c6 -d 10.10.2.0/24 -p udp
-A eth0_self -j ACCEPT -s 10.1.1.0/24 -d 224.0.0.18 -p 112
-A eth0_self -g c2 -d 10.1.1.0/30 -p icmp
COMMIT
*nat
:OUTPUT ACCEPT
:POSTROUTING ACCEPT
:PREROUTING ACCEPT
-A POSTROUTING -j SNAT -s 10.1.2.3 -d 192.168.1.16/29 --to-source 10.2.3.4
COMMIT
END
check_parse_and_unchanged($type, $minimal_device, $in, $out, $title);

############################################################
$title = "Parse routing with iptables";
############################################################
$in = <<END;
ip route add 10.10.0.0/16 via 10.1.2.3
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 22
END

$out = <<'END';
ip route add 10.10.0.0/16 via 10.1.2.3
iptables differs at [keys: <->filter]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 22
COMMIT
END

check_parse_and_unchanged($type, $minimal_device, $in, $out, $title);

############################################################
$title = "Change routing";
############################################################
$in = <<END;
ip route add 10.10.0.0/16 via 10.1.2.3
ip route add 10.20.0.0/16 via 10.1.2.3
ip route add 10.40.0.0/16 via 10.1.2.4
END

$device = <<END;
ip route add 10.20.0.0/16 via 10.1.2.3
ip route add 10.30.0.0/16 via 10.1.2.3
ip route add 10.40.0.0/16 via 10.1.2.3
END

$out = <<END;
ip route add 10.10.0.0/16 via 10.1.2.3
ip route del 10.40.0.0/16 via 10.1.2.3\\N ip route add 10.40.0.0/16 via 10.1.2.4
ip route del 10.30.0.0/16 via 10.1.2.3
END

eq_or_diff(approve($type, $device, $in), $out, $title);

############################################################
$title = "Change iptables port";
############################################################
$in = <<END;
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 22
COMMIT
END

$device = <<END;
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 23
COMMIT
END

$out = <<END;
iptables differs at filter:c3:RULES:0:--dport:[23<->22]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 22
COMMIT
END

eq_or_diff(approve($type, $device, $in), $out, $title);

############################################################
$title = "Remove iptables port";
############################################################
$in = <<END;
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp
COMMIT
END

$device = <<END;
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 23
COMMIT
END

$out = <<END;
iptables differs at filter:c3:RULES:0:[keys: --dport<->]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp
COMMIT
END

eq_or_diff(approve($type, $device, $in), $out, $title);

############################################################
$title = "Change iptables protocol";
############################################################
$in = <<END;
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p udp --dport 135
COMMIT
END

$device = <<END;
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p tcp --dport 135
COMMIT
END

$out = <<END;
iptables differs at filter:c3:RULES:0:-p:[tcp<->udp]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p udp --dport 135
COMMIT
END

eq_or_diff(approve($type, $device, $in), $out, $title);

############################################################
$title = "Add iptables rule";
############################################################
$in = <<END;
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p udp --dport 135
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p udp --dport 137
COMMIT
END

$device = <<END;
#!/usr/sbin/iptables-restore
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p udp --dport 135
COMMIT
END

$out = <<END;
iptables differs at filter:c3:RULES:[size: 1<->2]
#!/sbin/iptables-restore
# Generated by NetSPoC
*filter
:c3 -
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p udp --dport 135
-A c3 -j ACCEPT -s 10.1.11.111 -d 10.10.1.2 -p udp --dport 137
COMMIT
END

eq_or_diff(approve($type, $device, $in), $out, $title);

############################################################
$title = "Unknown command";
############################################################
$device = <<END;
foo
END

$in = '';

$out = <<END;
ERROR>>> Unknown command
ERROR>>>  at line 1, pos 0:
ERROR>>> >>foo<<
END

eq_or_diff(approve_err($type, $device, $in), $out, $title);

############################################################
$title = "Unexpected trailing '!'";
############################################################
$device = <<END;
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -p TCP --syn !
END

$in = '';

$out = <<END;
ERROR>>> Unexpected trailing \'!\'
ERROR>>>  at line 3, pos 10:
ERROR>>> >>-A FORWARD -i eth1 -j ACCEPT -p TCP --syn !<<
END

eq_or_diff(approve_err($type, $device, $in), $out, $title);

############################################################
$title = "Negation at option or at arg";
############################################################
$device = <<END;
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT ! -p TCP
END

$in = <<END;
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -p ! TCP
END

$out = '';

eq_or_diff(approve($type, $device, $in), $out, $title);

############################################################
$title = "TCP-flags as syn option ";
############################################################
$device = <<END;
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -p TCP ! --syn
END

$in = <<END;
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -p TCP ! --tcp-flags FIN,SYN,RST,ACK SYN
END

$out = '';

eq_or_diff(approve($type, $device, $in), $out, $title);

############################################################
$title = "Ignore option '-m' ";
############################################################

$device = <<END;
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -m tcp -p TCP
END

$in = <<END;
*filter
:FORWARD DROP
-A FORWARD -i eth1 -j ACCEPT -p TCP
END

$out = '';

eq_or_diff(approve($type, $device, $in), $out, $title);

############################################################
$title = "--set-mark and --xsetmark ";
############################################################

$device = <<END;
*mangle
:PREROUTING ACCEPT
-A PREROUTING -j MARK --set-xmark 0x01 -p TCP --dport 80
-A PREROUTING -j MARK --set-xmark 0x0f/0xffffffff -p TCP --dport 81
END

$in = <<END;
*mangle
:PREROUTING ACCEPT
-A PREROUTING -j MARK --set-mark 1 -p TCP --dport 80
-A PREROUTING -j MARK --set-mark 15 -p TCP --dport 81
END

$out = '';

eq_or_diff(approve($type, $device, $in), $out, $title);

############################################################
done_testing;
